//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demka1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProducts
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int PartnerId { get; set; }
        public Nullable<int> ProductCount { get; set; }

        public decimal TotalPrice
        {
            get
            {
                decimal? price = (decimal?)this.ProductCount * this.Products.MinimalPrice;
                return price.HasValue ? Math.Round(price.Value, 2) : 0;
            }
        }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
