//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demka1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.PartnerProducts = new HashSet<PartnerProducts>();
        }
    
        public int Id { get; set; }
        public int PartnershipId { get; set; }
        public string Name { get; set; }
        public string DirectorLN { get; set; }
        public string DirectorFN { get; set; }
        public string DirectorMN { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string RegisterAddressIndex { get; set; }
        public int RegionId { get; set; }
        public int CityId { get; set; }
        public string RegisterAddressStreet { get; set; }
        public string RegisterAddressHouse { get; set; }
        public string INN { get; set; }
        public Nullable<int> Rating { get; set; }

        public string PartnerAdress
        {
            get
            {
                string city = Cities.CityName;
                string region = Regions.RegionName;
                return $"{RegisterAddressIndex}, {region}, {city}, {RegisterAddressStreet}, {RegisterAddressHouse}";
            }
        }

        public string PartnerFullName
        {
            get
            {
                string type = PartnershipTypes.TypeName;
                return $"{type} | {Name}";
            }
        }
    
        public virtual Cities Cities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProducts> PartnerProducts { get; set; }
        public virtual PartnershipTypes PartnershipTypes { get; set; }
        public virtual Regions Regions { get; set; }
    }
}
